"""Validate all local asset paths referenced in README.md exist."""
import pathlib
import re

readme = pathlib.Path('README.md').read_text(encoding='utf-8')

# extract all src= and href= paths
local_paths = []
for m in re.finditer(r'src=["\'](?!https?://|mailto:|#)([^"\']+)["\']', readme):
    local_paths.append(m.group(1))
for m in re.finditer(r'href=["\'](?!https?://|mailto:|#)([^"\']+)["\']', readme):
    local_paths.append(m.group(1))

print(f'Found {len(local_paths)} local references')
missing = 0
for p in local_paths:
    if p.startswith('?'):
        continue
    # remove leading ./ for resolution
    resolved = pathlib.Path(p)
    if not resolved.exists():
        # maybe the 3D file is generated by CI later
        if 'profile-3d-contrib' in p:
            print(f'EXPECTED (CI): {p}')
            continue
        print(f'MISSING: {p}')
        missing += 1
    else:
        print(f'OK: {p}')
print(f'missing: {missing}')
